//! Claim extraction + skip-names filter.
//!
//! Extracted from scanner/mod.rs for code health.
//! - skip_names: 400+ language builtins + stdlib methods to skip
//! - ClaimPattern + claim_patterns: regex patterns for API call extraction
//! - RE_CLAIM_*: static Lazy regexes

use std::collections::HashSet;

use once_cell::sync::Lazy;
use regex::Regex;

pub(crate) fn skip_names() -> &'static HashSet<&'static str> {
    use std::sync::OnceLock;
    static SKIP: OnceLock<HashSet<&'static str>> = OnceLock::new();
    SKIP.get_or_init(|| {
        [
            // JS/TS keywords
            "if",
            "for",
            "while",
            "switch",
            "catch",
            "return",
            "function",
            "const",
            "let",
            "var",
            "class",
            "import",
            "export",
            "default",
            "new",
            "try",
            "throw",
            "typeof",
            "instanceof",
            "void",
            "delete",
            "break",
            "continue",
            "do",
            "else",
            "in",
            "of",
            "this",
            "super",
            "extends",
            "implements",
            "interface",
            "enum",
            "namespace",
            "declare",
            "abstract",
            "async",
            "await",
            "yield",
            "static",
            "readonly",
            "public",
            "private",
            "protected",
            "get",
            "set",
            // JS globals
            "console",
            "Math",
            "JSON",
            "Object",
            "Array",
            "String",
            "Number",
            "Boolean",
            "Promise",
            "Error",
            "Date",
            "RegExp",
            "Map",
            "Set",
            "Symbol",
            "Proxy",
            "Reflect",
            "WeakMap",
            "WeakSet",
            "BigInt",
            "globalThis",
            "window",
            "document",
            "fetch",
            "process",
            "global",
            "setTimeout",
            "setInterval",
            "setImmediate",
            "clearImmediate",
            "clearTimeout",
            "clearInterval",
            "queueMicrotask",
            "structuredClone",
            "atob",
            "btoa",
            "__dirname",
            "__filename",
            "encodeURI",
            "decodeURI",
            "encodeURIComponent",
            "decodeURIComponent",
            "parseInt",
            "parseFloat",
            "isNaN",
            "isFinite",
            "eval",
            // Node.js modules
            "fs",
            "path",
            "os",
            "http",
            "https",
            "crypto",
            "stream",
            "buffer",
            "url",
            "util",
            "events",
            "net",
            "tls",
            "zlib",
            "child_process",
            "worker_threads",
            "perf_hooks",
            "assert",
            "querystring",
            "dns",
            "dgram",
            "cluster",
            "readline",
            "repl",
            "vm",
            "tty",
            "string_decoder",
            "console",
            "module",
            "require",
            "exports",
            "process",
            // Python builtins
            "print",
            "range",
            "len",
            "str",
            "int",
            "float",
            "list",
            "dict",
            "tuple",
            "set",
            "bool",
            "type",
            "isinstance",
            "issubclass",
            "super",
            "property",
            "classmethod",
            "staticmethod",
            "open",
            "input",
            "format",
            "abs",
            "min",
            "max",
            "sum",
            "sorted",
            "enumerate",
            "zip",
            "map",
            "filter",
            "any",
            "all",
            "getattr",
            "setattr",
            "hasattr",
            "delattr",
            // Array prototype
            "push",
            "pop",
            "shift",
            "unshift",
            "splice",
            "slice",
            "concat",
            "indexOf",
            "lastIndexOf",
            "includes",
            "find",
            "findIndex",
            "findLast",
            "findLastIndex",
            "filter",
            "map",
            "reduce",
            "reduceRight",
            "forEach",
            "some",
            "every",
            "flat",
            "flatMap",
            "fill",
            "copyWithin",
            "reverse",
            "sort",
            "at",
            "entries",
            "join",
            "toReversed",
            "toSorted",
            "toSpliced",
            "with",
            "group",
            // String prototype
            "split",
            "trim",
            "trimStart",
            "trimEnd",
            "replace",
            "replaceAll",
            "match",
            "matchAll",
            "search",
            "substring",
            "substr",
            "toLowerCase",
            "toUpperCase",
            "toLocaleLowerCase",
            "toLocaleUpperCase",
            "toString",
            "valueOf",
            "charAt",
            "charCodeAt",
            "codePointAt",
            "startsWith",
            "endsWith",
            "includes",
            "repeat",
            "padStart",
            "padEnd",
            "normalize",
            "localeCompare",
            "at",
            "concat",
            "indexOf",
            "lastIndexOf",
            "fromCharCode",
            "fromCodePoint",
            "raw",
            // Object methods
            "keys",
            "values",
            "entries",
            "assign",
            "freeze",
            "isFrozen",
            "seal",
            "isSealed",
            "preventExtensions",
            "isExtensible",
            "getPrototypeOf",
            "setPrototypeOf",
            "getOwnPropertyNames",
            "getOwnPropertyDescriptor",
            "defineProperty",
            "defineProperties",
            "create",
            "fromEntries",
            "hasOwn",
            "is",
            "groupBy",
            // Promise methods
            "then",
            "catch",
            "finally",
            "resolve",
            "reject",
            "all",
            "allSettled",
            "race",
            "any",
            "withResolvers",
            // Function methods
            "call",
            "apply",
            "bind",
            // Math methods
            "floor",
            "ceil",
            "round",
            "trunc",
            "random",
            "abs",
            "sign",
            "max",
            "min",
            "pow",
            "sqrt",
            "cbrt",
            "exp",
            "log",
            "log2",
            "log10",
            "sin",
            "cos",
            "tan",
            "asin",
            "acos",
            "atan",
            "atan2",
            "hypot",
            "fround",
            "clz32",
            "imul",
            // RegExp methods
            "test",
            "exec",
            "compile",
            // Testing framework globals (vitest/jest) — also catches the
            // \n escape artifact where \ndescribe becomes ndescribe.
            "describe", "it", "expect", "beforeEach", "afterEach",
            "beforeAll", "afterAll", "vi", "before", "after",
            // Built-in classes
            "Response",
            "Request",
            "Buffer",
            "ServerResponse",
            "IncomingMessage",
            "ReadableStream",
            "WritableStream",
            "DuplexStream",
            "TransformStream",
            "TextDecoder",
            "TextEncoder",
            "URL",
            "URLSearchParams",
            "Headers",
            "FormData",
            "AbortController",
            "AbortSignal",
            "EventEmitter",
            "Uint8Array",
            "Uint16Array",
            "Uint32Array",
            "Int8Array",
            "Int16Array",
            "Int32Array",
            "Float32Array",
            "Float64Array",
            "BigUint64Array",
            "BigInt64Array",
            "DataView",
            "ArrayBuffer",
            "SharedArrayBuffer",
            "WeakRef",
            "FinalizationRegistry",
            "Readable",
            "Writable",
            "Duplex",
            "Transform",
            "Pipeline",
            "Iterator",
            "Generator",
            "AsyncGenerator",
            "AsyncIterator",
            // Framework vars
            "app",
            "req",
            "res",
            "ctx",
            "el",
            "doc",
            "server",
            "client",
            "db",
            "store",
            "router",
            "state",
            "props",
            "ref",
            "event",
            "target",
            "element",
            "node",
            "instance",
            "service",
            "handler",
            "controller",
            "view",
            "model",
            "collection",
            "schema",
            "config",
            // Common short vars
            "s",
            "st",
            "next",
            "prev",
            "opts",
            "args",
            "err",
            "val",
            "self",
            "that",
            "item",
            "idx",
            "key",
            "data",
            "result",
            "output",
            "value",
            "msg",
            "info",
            "context",
            "payload",
            "body",
            "header",
            // Rust stdlib methods (most common false positive sources)
            "unwrap",
            "unwrap_or",
            "unwrap_or_default",
            "unwrap_or_else",
            "unwrap_unchecked",
            "expect",
            "expect_err",
            "expect_none",
            "clone",
            "clone_from",
            "as_str",
            "as_bytes",
            "as_ref",
            "as_mut",
            "as_ptr",
            "as_u64",
            "as_u32",
            "as_usize",
            "as_i64",
            "as_i32",
            "as_bool",
            "as_f64",
            "to_string",
            "to_owned",
            "to_vec",
            "to_lowercase",
            "to_uppercase",
            "to_ascii_lowercase",
            "to_ascii_uppercase",
            "parse",
            "from_str",
            "from",
            "into",
            "into_iter",
            "iter",
            "iter_mut",
            "into_bytes",
            "collect",
            "fold",
            "for_each",
            "enumerate",
            "zip",
            "chain",
            "take",
            "skip",
            "take_while",
            "skip_while",
            "peekable",
            "rev",
            "step_by",
            "flat_map",
            "flatten",
            "inspect",
            "scan",
            "partition",
            "try_fold",
            "try_for_each",
            "any",
            "all",
            "count",
            "max",
            "min",
            "sum",
            "product",
            "nth",
            "last",
            "reduce",
            "len",
            "is_empty",
            "push_str",
            "push_back",
            "push_front",
            "pop_back",
            "pop_front",
            "extend",
            "extend_from_slice",
            "truncate",
            "clear",
            "insert",
            "remove",
            "swap_remove",
            "retain",
            "get",
            "get_mut",
            "get_or_insert",
            "entry",
            "or_insert",
            "or_default",
            "or_insert_with",
            "keys",
            "values",
            "starts_with",
            "ends_with",
            "find",
            "rfind",
            "contains",
            "replace",
            "replacen",
            "trim",
            "trim_start",
            "trim_end",
            "trim_matches",
            "split",
            "splitn",
            "rsplit",
            "split_whitespace",
            "lines",
            "chars",
            "bytes",
            "lock",
            "try_lock",
            "read",
            "write",
            "read_to_string",
            "read_line",
            "send",
            "recv",
            "try_send",
            "try_recv",
            "spawn",
            "join",
            "block_on",
            "poll",
            "eq",
            "ne",
            "cmp",
            "partial_cmp",
            "lt",
            "le",
            "gt",
            "ge",
            "hash",
            "borrow",
            "deref",
            "deref_mut",
            "fmt",
            "display",
            "debug",
            "Ok",
            "Err",
            "Some",
            "None",
            "Result",
            "Option",
            "Vec",
            "String",
            "Box",
            "Arc",
            "Rc",
            "RefCell",
            "Mutex",
            "HashMap",
            "HashSet",
            "BTreeMap",
            "BTreeSet",
        ]
        .into_iter()
        .collect()
    })
}

// ---------------------------------------------------------------------------
// Regex patterns for API claim extraction.
//
// Compiled once via `once_cell::Lazy` and reused across every scan. The old
// per-call `claim_patterns()` constructor reallocated + recompiled 3 regex
// objects on every invocation of `extract_api_claims` (~5ms wasted per scan
// on a 100-request session — 500ms of pure regex compilation overhead).

static RE_CLAIM_CLASS_METHOD: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"\b([A-Z][a-zA-Z_]+)\.([a-zA-Z_][a-zA-Z0-9_]*)\(").unwrap()
});

static RE_CLAIM_OBJ_METHOD: Lazy<Regex> = Lazy::new(|| {
    Regex::new(r"(?:^|[^a-zA-Z0-9_])([a-z_][a-zA-Z_]+)\.([a-zA-Z_][a-zA-Z0-9_]*)\(").unwrap()
});

static RE_CLAIM_BARE_CALL: Lazy<Regex> = Lazy::new(|| {
    // Allow camelCase + all-lowercase names ≥3 chars (was lowercase-only,
    // which silently missed every camelCase hallucinated function call).
    Regex::new(r"(?:^|[^a-zA-Z0-9_.])([a-zA-Z_][a-zA-Z0-9_]{2,})\(").unwrap()
});

// Import / module claims — catches the DELULU "import" hallucination type
// (476 samples) where the LLM invents a module that doesn't resolve.
// Matches:
//   import { X, Y } from 'pkg'           (JS/TS)
//   import { X } from "pkg/sub"          (JS/TS)
//   import pkg from 'pkg'                (JS/TS default)
//   import * as ns from 'pkg'            (JS/TS namespace)
//   from 'pkg' import X                  (Python)
//   from pkg import X                    (Python)
//   const x = require('pkg')             (JS CommonJS)
//   #include <header.h>                  (C/C++)
//   use pkg::X                           (Rust)
//   #include "header.hpp"                (C/C++)
static RE_CLAIM_IMPORT_FROM: Lazy<Regex> = Lazy::new(|| {
    // Captures the package path from `... from 'pkg'` / `... from "pkg"`.
    Regex::new(r#"\bfrom\s+['"]([^'"]+)['"]"#).unwrap()
});

static RE_CLAIM_IMPORT_STMT: Lazy<Regex> = Lazy::new(|| {
    // Captures the module from `import 'pkg'` / `import "pkg"` (side-effect import).
    Regex::new(r#"\bimport\s+['"]([^'"]+)['"]"#).unwrap()
});

static RE_CLAIM_PYTHON_FROM: Lazy<Regex> = Lazy::new(|| {
    // Python: `from pkg import X` — capture pkg.
    Regex::new(r"\bfrom\s+([a-zA-Z_][a-zA-Z0-9_.]*)\s+import\b").unwrap()
});

static RE_CLAIM_REQUIRE: Lazy<Regex> = Lazy::new(|| {
    // JS CommonJS: `require('pkg')`.
    Regex::new(r#"\brequire\s*\(\s*['"]([^'"]+)['"]"#).unwrap()
});

static RE_CLAIM_INCLUDE: Lazy<Regex> = Lazy::new(|| {
    // C/C++: `#include <header>` or `#include "header"`.
    Regex::new(r#"#include\s+[<"]([^>"]+)[>"]"#).unwrap()
});

/// Claim-pattern descriptor used by `extract_api_claims`. Holds a reference
/// to the static regex + the kind label.
pub(crate) struct ClaimPattern {
    pub(crate) re: &'static Lazy<Regex>,
    pub(crate) kind: &'static str,
}

pub(crate) fn claim_patterns() -> Vec<ClaimPattern> {
    vec![
        ClaimPattern { re: &RE_CLAIM_CLASS_METHOD, kind: "class_method" },
        ClaimPattern { re: &RE_CLAIM_OBJ_METHOD, kind: "obj_method" },
        ClaimPattern { re: &RE_CLAIM_BARE_CALL, kind: "bare_call" },
        ClaimPattern { re: &RE_CLAIM_IMPORT_FROM, kind: "import" },
        ClaimPattern { re: &RE_CLAIM_IMPORT_STMT, kind: "import" },
        ClaimPattern { re: &RE_CLAIM_PYTHON_FROM, kind: "import" },
        ClaimPattern { re: &RE_CLAIM_REQUIRE, kind: "import" },
        ClaimPattern { re: &RE_CLAIM_INCLUDE, kind: "import" },
    ]
}